config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy'
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes, as: votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, as: votable
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user_id = session[:user_id]

    if @answer.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_answer_path(@answer)
    else
      render :edit
    end
  end


  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_user(user_id)
    session[:user_id] = user_id
  end

  helper_method :current_user
  helper_method :login_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    @question.user_id = session[:user_id]
      if @question.save
        flash[:notice] = "Question saved!"
        redirect_to questions_path
      else
        render :new
      end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

private
  def question_params
    params.require(:question).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You signed in!"
      redirect_to user
    else
      flash[:alert] = "You are not who you say you are..."
      redirect_to :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      redirect_to @user
    else
      flash[:alert] = "We were unable to sign you up!"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<%end%>

app/views/answers/edit.html.erb
<%=render 'form'%>

app/views/answers/new.html.erb
<%= render 'form' %>

app/views/answers/show.html.erb
<h1><%= @answer.content %></h1>

<%= link_to 'Edit This Answer', edit_question_answer_path(@answer.question, @answer) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackoverflowClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
  
    <%= link_to "Sign Out", '/logout', data: {confirm: "Do your parents know you're signing out?", method: :delete} %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<%end%>

app/views/questions/edit.html.erb
<h1>Update <%=@question.content%></h1>


<%= render 'form'%>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <h1><%= link_to question.content, question_path(question) %></h1>
  <h4> by: <%= question.user.name %></h4>
<%end%>

app/views/questions/new.html.erb
<%= render 'form' %>

<h2><%=link_to "All Questions", questions_path%></h2>

app/views/questions/show.html.erb
<h1><%= @question.content %></h1>

<% @question.answers.each do |answer| %>
  <h1><%= link_to answer.content, question_answer_path(@question, answer) %></h1>
  <h4> by: <%= answer.user.name %></h4>
<%end%>


<%= link_to 'Answer This Question', new_question_answer_path(@question) %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<%end%>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <h1><%= link_to user.name, user_path(user) %></h1>
<%end%>

app/views/users/new.html.erb
<%= render 'form' %>

<h2><%=link_to "All Users", users_path%></h2>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.questions.any? %>
  <ul>
    <% @user.questions.each do |question| %>
      <li><%= link_to question.content, edit_question_path(question) %></li>
    <%end%>
  </ul>
<%else%>
  <h3>No questions yet!</h3>
<%end%>

<%=link_to "Add a Question", new_question_path%>